services:
  app_proxy:
    environment:
      APP_HOST: ilya-auto-h265-video-converter_server_1
      APP_PORT: 8080

  server:
    image: ghcr.io/ilyasweg-ai/ilya-auto-h265-video-converter:0.1.6
    restart: on-failure
    environment:
      APP_PORT: "8080"
      DATA_DIR: /data
      DEFAULT_INPUT_PATH: /media/ssd990_main/porn
      DEFAULT_OUTPUT_PATH: /media/ssd990_main/new
      DEFAULT_FAILED_PATH: /media/ssd990_main/failed_convert
      DEFAULT_TEMP_PATH: /media/ssd990_main/temp_convert
      FFMPEG_THREADS: "0"
    volumes:
      - ${UMBREL_ROOT}/app-data/ilya-auto-h265-video-converter/data:/data
      - ${UMBREL_ROOT}/external:/media
